# Generated by Django 5.1.1 on 2024-09-10 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
                ('modopreparo', models.TextField()),
                ('tempopreparo', models.DurationField()),
                ('categoria', models.CharField(max_length=80)),
                ('datacriacao', models.DateTimeField()),
                ('publi_priva', models.BooleanField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.recipe')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.user')),
            ],
        ),
    ]
